// src/components/ContentSelected.vue
<template>
  <div class="content-selected">
    a
    <the-game v-if="compGame"></the-game>
    <todd-page v-if="compTodd"></todd-page>
    <about-page v-if="compAbout"></about-page>
  </div>
</template>

<script>
export default {
  name: "ContentSelected",
  props: {
    selection: String,
    compGame: Boolean,
    compTodd: Boolean,
    compAbout: Boolean,
  },
  components: {
    theGame: () =>
      import(/* webpackChunkName: "theGame" */ "./lit/pages/the-game.js"),
    toddPage: () =>
      import(/* webpackChunkName: "toddPage" */ "./lit/pages/todd-page.js"),
    aboutPage: () =>
      import(/* webpackChunkName: "aboutPage" */ "./lit/pages/about-page.js"),
  },
  created() {
    this.compTodd = false;
    this.compGame = false;
    this.compAbout = false;
    if (this.selection == "game") this.compGame = true;
    if (this.selection == "todd") this.compTodd = true;
    if (this.selection == "about") this.compAbout = true;
  },
};
</script>

<style scoped>
* {
  color: #2e586c;
  font-family: "Roboto", arial, sans-serif;
}
.intro,
.author {
  margin: 10px 10px;
}
.intro {
  font-size: 16px;
}
.author {
  margin: 20px 10px;
  font-size: 19px;
}
</style>

// src/components/lit/content-selected.js
import { LitElement, html, css } from "lit-element";

import "@/components/lit/pages/about-page.js";
import "@/components/lit/pages/the-game.js";
import "@/components/lit/pages/todd-page.js";

class ContentSelected extends LitElement {
  static get properties() {
    return {
      selection: { type: String },
    };
  }

  constructor() {
    super();
    this.selection = "";
  }

  static get styles() {
    return [css``];
  }

  render() {
    const gamePage = () =>
      html`
        <the-game></the-game>
      `;
    const toddPage = () =>
      html`
        <todd-page></todd-page>
      `;
    const aboutPage = () =>
      html`
        <about-page></about-page>
      `;
    return html`
      <div class="content-selected">
        a${this.selection}a ${this.compGame() ? gamePage() : ""}
        ${this.compTodd() ? toddPage() : ""}
        ${this.compAbout() ? aboutPage() : ""}
      </div>
    `;
  }
  compGame() {
    return this.selection == "game";
  }
  compTodd() {
    return this.selection == "todd";
  }
  compAbout() {
    return this.selection == "about";
  }
}
// Register the new element with the browser.
customElements.define("content-selected", ContentSelected);
